Repository RenatoCespedes/playlist-project, pull requests merged in 2023-01, with the labels that each got.

#2 Feature/create model playlist
  prisma/schema.prisma
Labels: feature

#5 Change/change attributes in models prisma
  prisma/schema.prisma
Labels: fix relations bd

#8 Feature/create component playlist
  src/components/playlist/controller.ts
  src/components/playlist/index.ts
Labels: feature

#10 Update/index route from component playlist
  src/components/index.ts
  src/components/playlist/index.ts
Labels: change

#11 feature: add find all Users
  src/components/index.ts
  src/components/songs/controller.ts
  src/components/users/controller.ts
  src/components/users/index.ts
Labels: feature

#13 Feature/add create users
  prisma/schema.prisma
  src/components/users/controller.ts
Labels: feature

#14 Change urlenv to file
  prisma/schema.prisma
Labels: change

#15 Feature/generate devdb and migrations
  prisma/dev.db
  prisma/dev.db-journal
  prisma/migrations/20230121225849_init/migration.sql
  prisma/migrations/migration_lock.toml
Labels: generate

#16 Feature/include songs in playlists
  src/components/playlist/controller.ts
Labels: feature, change

#17 Feature/fix data to create playlist
  src/components/playlist/controller.ts
Labels: change, fixed

#18 Feature/add music in a playlist
  src/components/playlist/controller.ts
  src/components/playlist/index.ts
Labels: feature

#19 Feature/change index create app in src
  src/app.ts
  src/index.ts
Labels: feature, change

#21 fix user
  src/components/users/controller.ts
  src/components/users/index.ts
Labels: change

#23 update of package in package.json
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: feature, change

#24 Feature/bcrypt and hash password
  src/app.ts
  src/components/users/controller.ts
Labels: feature, change

#27 Change/update field song and controller
  prisma/dev.db
  prisma/migrations/20230123212317_new/migration.sql
  prisma/schema.prisma
  src/components/songs/controller.ts
Labels: change

#28 Change/playlist user token
  src/components/playlist/controller.ts
Labels: feature, change
